### ISSUE TITLE
What to do with refresh token

### ISSUE THREAD

**Issue by FilthyNoempt** [noormi/oAuth#10]
What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token | What to do with refresh token |

**Comment by noormi** [comment]
Nothing, stop spamming issues
